npgsql/doc

conceptual/Npgsql/release-notes/4.1.md

I'm not sure if you want this as a breaking change, as it is only breaking for people that compile with warn as error. But most sensible people do :)

Document that `SslStream` has been obsoleted

---

conceptual/Npgsql/index.md
conceptual/Npgsql/installation.md
conceptual/Npgsql/toc.md

Because our very first index page shouldn't contain stuff like GAC installation and App.Config...

Move installation information out to a new page

---

index.md

Updated License link in https://github.com/npgsql/doc/blob/master/index.md for https://www.npgsql.org/

updated License link

---

conceptual/EFCore.PG/mapping/full-text-search.md

Could possibly drop the `.Where` ¯\_(ツ)_/¯

Added `.OrderByDescending` `Rank` example

---

conceptual/EF6.PG/index.md

Code-based configuration is not the only way to use Npgsql, and configuration files are easily adopted when deploying to different environments. By including this in the documentation, users get a better understanding of how to use Npgsql in various deployment configurations.

Show config file configuration

---

conceptual/Npgsql/performance.md

My understanding is that when writing large values, we are using the socket's send buffer so we should be controlling the `Socket Send Buffer Size` connection string parameter, NOT the receive parameter (this looks like a copy-and-paste error from a similar sentence in the `Reading Large Values` section).

Fix typo referencing "Socket Receive Buffer Size"

---

index.md

The link from the npgsql.com to its github page is not so obvious.
Maybe this is a good place to add it.

Added link from npgsql.com to its github page.

---

conceptual/Npgsql/types/basic.md

The following sentence:
> Provider-specific types are returne by...
Should read:
> Provider-specific types are **returned** by...

Fix typo in basic.md

---

conceptual/EFCore.PG/mapping/nodatime.md
conceptual/EFCore.PG/mapping/nts.md
conceptual/EFCore.PG/mapping/translations.md
conceptual/EFCore.PG/release-notes/6.0.md

Includes documentation on the timestamp handling changes.
Closes #115
@vonzshik @NinoFloris this is the EF Core side of things - I will work on the ADO.NET notes later today.
(don't forget these are docs so we can always improve them later - we should merge these soon since that needs to happen before we release rc1)

EF Core 6.0 release and breaking change notes

---

conceptual/Npgsql/index.md
conceptual/Npgsql/release-notes/6.0.md

See npgsql/npgsql#4106
/cc @vonzshik

Breaking change note on DbType.DateTime

---

conceptual/EFCore.PG/mapping/full-text-search.md

Without this it won't make a GIN index which is useless for FTS.

Add missing .HasMethod("GIN") in FTS example

---

conceptual/EFCore.PG/mapping/enum.md

As https://github.com/npgsql/efcore.pg/pull/1183 was merged long time ago, it seems the documentation regarding enum altering was not updated. This adds a mention that adding enum values is supported.

Update enum docs to mention add support

---

conceptual/EFCore.PG/mapping/enum.md

Enum labels require quotes around them here otherwise you'll get a syntax error.

Put quotes around enum labels in the ALTER TYPE statement

---

conceptual/Npgsql/release-notes/6.0.md

The sentence:
> ...which were designed to **provider** the same APIs...
Should read:
> ...which were designed to **provide** the same APIs...

Fix typo in 6.0 release notes

---

conceptual/Npgsql/basic-usage.md

Fix mix-ups between `CommandType` and `CommandBehaviour` (e.g. `CommandBehavior.StoredProcedure` should be `CommandType.StoredProcedure`).

Fix typos in basic-usage.md

---

conceptual/Npgsql/diagnostics/logging.md

The sentence:
> ...messages with a given level or above to **stdanrd** output.
Should read:
> ...messages with a given level or above to **standard** output.

Fix typo in logging.md

---

conceptual/Npgsql/connection-string-parameters.md

The sentence:
> ...trying to execute **a an** internal command
Should read:
> ...trying to execute **an** internal command
The sentence:
> ...**althoug** not all of them... 
Should read:
> ...**although** not all of them...

Fix typos in connection-string-parameters.md

---

.github/workflows/build-documentation.yml

In Npgsql and EFCore.PG, instead of from the stable branch, which I'm deleting. We used to merge releases to stable, but that's just a hassle.

Build API documentation from docs branches

---

conceptual/EFCore.PG/misc/collations-and-case-sensitivity.md

qu**o**te limited -> qu**i**te limited

Fix typo in collations-and-case-sensitivity.md

---

conceptual/Npgsql/types/basic.md

I noticed that support for writing a CLR Stream into a bytea column was added in https://github.com/npgsql/npgsql/issues/4466
I've been using it and it works great. I noticed the documentation needed an update to indicate this was a possibility

Update write mapping to include Stream->bytea for npgsql 7+

---

conceptual/Npgsql/basic-usage.md

In the Npgsql documentation, replaced the usage of `cmd.ExecuteReaderAsync()` with `batch.ExecuteReaderAsync()` to match the latest NpgsqlBatch API. This ensures that the documentation reflects the correct usage of NpgsqlBatch for executing commands and reading results.

docs: Update NpgsqlBatch usage example

---

conceptual/EFCore.PG/modeling/indexes.md
conceptual/EFCore.PG/modeling/tables.md
conceptual/EFCore.PG/release-notes/8.0.md
conceptual/EFCore.PG/toc.yml

Following https://github.com/npgsql/efcore.pg/pull/2914

Documentation on storage parameters

---

conceptual/EFCore.PG/release-notes/3.1.md
conceptual/EFCore.PG/release-notes/5.0.md
conceptual/EFCore.PG/release-notes/6.0.md
conceptual/EFCore.PG/release-notes/7.0.md
conceptual/EFCore.PG/release-notes/8.0.md
conceptual/Npgsql/release-notes/3.1.md
conceptual/Npgsql/release-notes/3.2.md
conceptual/Npgsql/release-notes/4.0.md
conceptual/Npgsql/release-notes/4.1.md
conceptual/Npgsql/release-notes/7.0.md
conceptual/Npgsql/release-notes/8.0.md

Patch contributions without an assigned issue are still missing. This will follow in a separate PR after updating the generator program at some point.

Update contributors in release notes.

---

conceptual/EFCore.PG/mapping/translations.md

This pr fixes text appearing in wrong columns caused by not escaped pipe characters.

Escape pipes in string translations doc

---

conceptual/Npgsql/security.md

Document the non-periodic password provider

---

conceptual/Npgsql/connection-string-parameters.md
conceptual/Npgsql/release-notes/9.0.md
conceptual/Npgsql/security.md

We can probably add a few links to our API and I still have to go over all the changes we did (like update connection string parameters), but overall should be good.

Add release notes for Npgsql 9

---

conceptual/Npgsql/diagnostics/tracing.md
conceptual/Npgsql/release-notes/9.0.md

And reorganize the 9.0 release notes a bit.
/cc @vonzshik

Document the new 9.0 tracing features

---

conceptual/Npgsql/connection-string-parameters.md

Connection string parameters EF Template Database and EF Admin Database removed in 8.0

EF parameters removed in 8.0

---

conceptual/Npgsql/types/basic.md

I believe this code embed was formerly closed too early and therefore it messed up some styling.

fix: broken code embedding
