npgsql/doc

dev/types.md, docs/dev/types.html
Follow up to https://github.com/npgsql/npgsql/pull/1814
@Emill @roji
=> Document postgresql tsquery phrase operator format.

docs/styles/docfx.css
Fixes #8 
Hopefully not stepping on any toes, but I seen it's been awhile since this has been reported. Fixed with the solution in the issue, but open to changes!
=> fix: logo hover color

conceptual/Npgsql/release-notes/5.0.md
See https://github.com/npgsql/npgsql/pull/1996 and
https://github.com/npgsql/npgsql/issues/443
=> Add announcement for reading/writing arrays of nullable value types

conceptual/EFCore.PG/modeling/concurrency.md
Added closing backticks for code fragment
=> Fix code fragment

conceptual/EF6.PG/index.md
Based on various input on https://github.com/npgsql/EntityFramework6.Npgsql/issues/8.
=> Show how to use optimistic concurrency using xmin

conceptual/Npgsql/release-notes/4.1.md
Hey @roji  and @YohDeadfall,
what do you think about this?
If you like it, I can create it for the other releases too.
=> Add contibutors to the release notes

conceptual/Npgsql/release-notes/5.0.md
Milestone fixed from 5.0 to 5.0.0 (including broken links)
=> Fix release note for milestone 5.0.0

index.md
And remove Appveyor/Travis
/cc @YohDeadfall @Brar @vonzshik @manandre @warcha
=> Update contributors list

conceptual/EFCore.PG/mapping/json.md, conceptual/EFCore.PG/modeling/generated-properties.md, conceptual/EFCore.PG/modeling/indexes.md, conceptual/EFCore.PG/release-notes/5.0.md, conceptual/EFCore.PG/toc.yml
Plus add docs for:
* Computed columns in 5.0
* IsCreatedConcurrently
* [JsonPropertyName]
/cc @Brar @YohDeadfall @vonzshik 
/cc @ajcvickers @JeremyLikness @AndriySvyryd @bricelam @smitpatel @maumar
=> Release notes for the EFCore.PG 5.0 release

conceptual/EFCore.PG/mapping/translations.md
See https://github.com/npgsql/efcore.pg/issues/1592
=> Document ltree support in EFCore.PG

conceptual/Npgsql/faq.md
=> Add FAQ question on broken connections and pooling

conceptual/Npgsql/connection-string-parameters.md
* Document Root Certificate and Client Certificate Key parameters
* Document environment variables
=> Connection string parameter doc changes

conceptual/Npgsql/release-notes/6.0.md
See https://github.com/npgsql/npgsql/issues/4027
/cc @NinoFloris
=> Breaking change note on parameter case-insensitivity

.markdownlint.json, conceptual/EFCore.PG/release-notes/6.0.md, conceptual/Npgsql/release-notes/6.0.md, conceptual/Npgsql/types/basic.md, conceptual/Npgsql/types/datetime.md
And generally improve type mapping docs
=> Update date/time docs for 6.0

conceptual/Npgsql/connection-string-parameters.md, conceptual/Npgsql/release-notes/6.0.md, conceptual/Npgsql/security.md
Merge after releasing 6.0.0-rc.2
=> Docs on SSL changes in 6.0

conceptual/EFCore.PG/mapping/range.md, conceptual/EFCore.PG/release-notes/6.0.md, conceptual/Npgsql/release-notes/6.0.md
And patch up some range stuff too
Merge after releasing 6.0.0-rc.2
=> Add documentation on multiranges

conceptual/EFCore.PG/mapping/nodatime.md
See https://github.com/npgsql/efcore.pg/pull/2055
=> Document NodaTime timezone conversion translations

conceptual/Npgsql/release-notes/6.0.md, conceptual/Npgsql/security.md
See https://github.com/npgsql/npgsql/issues/4091
/cc @vonzshik
=> Revert certificate revocation being on by default

conceptual/EFCore.PG/modeling/generated-properties.md
Also update GUID generation while we're at it
=> Add docs on timestamp generation

conceptual/EFCore.PG/release-notes/6.0.md
See https://github.com/npgsql/efcore.pg/issues/2062
=> Release note on EF support for PG14 column compression

conceptual/EFCore.PG/release-notes/6.0.md, conceptual/Npgsql/release-notes/6.0.md
See https://github.com/npgsql/efcore.pg/issues/2098
=> Breaking change note on default mapping to multirange

conceptual/Npgsql/diagnostics.md, conceptual/Npgsql/release-notes/6.0.md
Plus a breaking change note on NpgsqlStatement.
=> Add info on exceptions and notices

conceptual/Npgsql/release-notes/6.0.md
See npgsql/npgsql#4177
/cc @vonzshik
=> Breaking change note on DBNull in arrays

conceptual/Npgsql/release-notes/6.0.md, conceptual/Npgsql/types/basic.md, conceptual/Npgsql/types/datetime.md
See https://github.com/npgsql/npgsql/issues/4135
=> Breaking change note on interval and TimeSpan

conceptual/Npgsql/release-notes/6.0.md
See https://github.com/npgsql/npgsql/issues/4227
=> Document the switch back to case-insensitive parameter matching

conceptual/Npgsql/basic-usage.md, conceptual/Npgsql/index.md
* Show basic connection usage, brief discussion of pooling
* Basic command usage
* Show positional parameter placeholders, discuss placeholders
* Batching
/cc @vonzshik @NinoFloris @brar, will merge this but in case you guys have suggestions/ideas we can improve further
=> Improve the basic usage page

conceptual/EFCore.PG/misc/other.md, conceptual/EFCore.PG/modeling/indexes.md
See https://github.com/npgsql/efcore.pg/issues/2265
=> Add caution note for instance SSL callbacks

conceptual/Npgsql/types/enums_and_composites.md
"SomeType" is PascalCase.
"someType" is camelCase.
=> Fix case name

conceptual/EFCore.PG/misc/collations-and-case-sensitivity.md, conceptual/EFCore.PG/release-notes/7.0.md
=> Document obsoletion of EF default column collations

conceptual/Npgsql/release-notes/6.0.md
=> Add 6.0 breaking change note for SSL Mode

conceptual/EFCore.PG/mapping/json.md
In particular adding an example for root level JSON strings
=> Improve scalar wrapping note

conceptual/Npgsql/types/jsonnet.md
The text:
> ...by perform serialization/deserialization...
Should read: 
> ...by **performing** serialization/deserialization...
=> Fix typo in jsonnet.md

conceptual/Npgsql/security.md
See https://github.com/npgsql/npgsql/issues/4309
=> Update docs on SSLMode.Require

conceptual/Npgsql/installation.md
The following sentence:
> In **additional** to the official releases, ...
Should read:
> In **addition** to the official releases, ...
The following sentence:
> To use it, add ... to **yuor** NuGet.Config.
Should read:
> To use it, add ... to **your** NuGet.Config.
The following sentence:
> However, if **you're like** to give it a try, ...
Should read:
> However, if **you'd like** to give it a try, ...
=> Fix multiple typos in installation.md

conceptual/Npgsql/types/geojson.md
=> correct GeoJSON Setup

conceptual/Npgsql/basic-usage.md, conceptual/Npgsql/release-notes/6.0.md, conceptual/Npgsql/release-notes/7.0.md, conceptual/Npgsql/toc.yml
See https://github.com/npgsql/npgsql/pull/4706
=> Document CommandType.StoredProcedure breaking change

conceptual/EFCore.PG/release-notes/7.0.md, conceptual/Npgsql/diagnostics/logging.md, conceptual/Npgsql/release-notes/7.0.md
=> Document the new Microsoft.Extensions.Logging support

conceptual/Npgsql/release-notes/6.0.md, conceptual/Npgsql/release-notes/7.0.md
=> Typo fix in version

conceptual/Npgsql/release-notes/7.0.md
=> Fix typo in documentation

conceptual/Npgsql/release-notes/7.0.md
=> Add some more info to the stored procedure breaking note

conceptual/Npgsql/basic-usage.md, conceptual/Npgsql/failover-and-load-balancing.md
=> Add documentation on NpgsqlDataSource

.github/workflows/build-documentation.yml, conceptual/Npgsql/release-notes/8.0.md
=> Update to docfx 2.60.0 and switch to .NET Core

conceptual/Npgsql/connection-string-parameters.md
=> Correct TCP keepalive connection string docs

conceptual/EFCore.PG/mapping/enum.md, conceptual/EFCore.PG/mapping/nodatime.md, conceptual/EFCore.PG/mapping/nts.md
=> Update EFCore.PG docs for NpgsqlDataSource usage

conceptual/EFCore.PG/mapping/enum.md
Discussed in https://github.com/npgsql/efcore.pg/issues/2815#issuecomment-1641927465
=> Enums types reload after migration fix.

conceptual/Npgsql/types/geojson.md
Updates a `;;` to be `;` in one of the c# examples
=> Update geojson.md to correct a minor typo

conceptual/EFCore.PG/release-notes/8.0.md, conceptual/Npgsql/release-notes/8.0.md, conceptual/Npgsql/types/json.md
/cc @vonzshik @NinoFloris @Brar
=> EFCore.PG 8.0 release notes

conceptual/EFCore.PG/release-notes/8.0.md, conceptual/Npgsql/release-notes/8.0.md
/cc @vonzshik @NinoFloris @Brar
=> Document more breaking changes

conceptual/Npgsql/connection-string-parameters.md, conceptual/Npgsql/release-notes/8.0.md
The list of new features is obviously a bit subjective, based on what I thought was worth mentioning front-and-center - of course we can always tweak it.
There are also still some minor missing breaking changes, we'll add these.
=> Some more release notes and obsoletions

conceptual/Npgsql/release-notes/8.0.md
=> Breaking change note for void-returning functions

conceptual/Npgsql/dev/release-checklist.md, conceptual/Npgsql/toc.yml
@vonzshik @NinoFloris @Brar here are the instructions for publishing a release - just so we have it written down somewhere. 
Closes #222
=> Add release checklist notes

conceptual/EFCore.PG/index.md
See https://github.com/npgsql/npgsql/issues/4523#issuecomment-2590392427
=> Amend getting started example for externally provided NpgsqlDataSource

conceptual/Npgsql/types/basic.md
=> Update basic types docs for binary type access

conceptual/Npgsql/security.md
=> Mention SASL as supported password management mechanism

conceptual/EFCore.PG/mapping/translations.md
=> Document fuzzy text search translations

.markdownlint.json, conceptual/Npgsql/basic-usage.md
=> Remove note on nullable value types and NpgsqlParameter<T>

conceptual/Npgsql/types/enums_and_composites.md
=> Add note on using DataTypeName when preparing with enum/composite

conceptual/Npgsql/prepare.md
=> Tweak Prepare docs around parameters
